---
Name: DevTools
After: '*'
---
Director:
  rules:
    'dev': 'DevelopmentAdmin2'
    
    
DevelopmentAdmin2:
  registered_controllers:
    build:
      controller: 'DevBuildController'
      links:
        build: 'Build/rebuild this environment. Call this whenever you have updated your project sources'
    tests:
      controller: 'TestRunner'
      links:
        tests: 'See a list of unit tests to run'
        'tests/all': 'Run all tests'
    jstests:
      controller: 'JSTestRunner'
      links: 
        jstests: 'See a list of JavaScript tests to run'
        'jstests/all': 'Run all JavaScript tests'
    tasks:
      controller: 'TaskRunner'
      links:
        tasks: 'See a list of build tasks to run'
    logs:
      controller: 'DevErrorLogsController'
      links:
        logs: 'Error Logs'
    tools:
      controller: 'DevToolsController'
      links:
        tools: 'Test tools'
    info:
      controller: 'DevInfoController'
      links:
        info: 'View application info'
        info/php: 'View php info'
   