---
Name: DevTools
After: '*'
---
DevelopmentAdmin:
  registered_controllers:
    logs:
      controller: 'DevErrorLogsController'
      links:
        logs: 'Error Logs'
    tools:
      controller: 'DevToolsController'
      links:
        tools: 'Test tools'
    info:
      controller: 'DevInfoController'
      links:
        info: 'View application info'
        info/php: 'View php info'
   